name: Deploy docs

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deployment:
    name: Deploy docs
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: checkout code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm install
      # generate api docs
      - run: pnpm typedoc

      - name: Deploy gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
